    SOLIC.FEC_REGISTRO_ALTA AS FECHA_REG_SOL 
    SOLIC.CVE_ID_SOLIC_INCAP_MATERNAL AS ID_SOL
    ASEG.CVE_ID_ASEGURADA_IM AS ID_ASEG
    ASEG.CURP
    ASEG.NSS
    DITPERSONA.NOM_NOMBRE
    DITPERSONA.NOM_PRIMER_APELLIDO
    DITPERSONA.NOM_SEGUNDO_APELLIDO
    ASEG.CORRREO_ASEGURADA
    ASEG.TELEFONO
    DELEG.CLAVE_DELEGACION AS DELEG_ASEG
    DELEG.DES_DELEG AS DES_DELEG_ASEG
    UMF.NOM_UNIDAD AS NOM_UNIDAD_ASEG
    CONS.CVE_NUM_CONSULTORIO AS NUM_CONS_ASEG
    CONSTUR.CVE_ID_TURNO AS TURNO_ASEG
    ASEG.NUM_CTA_CLABE
    BANCO.CVE_BANCO
    ASEG.FEC_PROB_PARTO AS FECHA_PROB_PARTO
    ASEG.FEC_ULT_MENSTRUACION AS FECHA_ULTIMA_MENSTRUACION
    ASEG.FEC_REGISTRO_ALTA  AS FECHA_REG_ASEGURADA
    MOTRECHAZO.CVE_ID_MOTIVO_RECHAZO
    CATMOTRECHAZO.DES_MOTIVO_RECHZO
    MST.MATRICULA  AS MATRICULA_MED_ST
    MDPM.MATRICULA AS MATRICULA_MED_DPM
    MDPM.DELEGACION AS DELEGACION_MED_DPM
    MDPM.UNIDAD AS UNIDAD_MED_DPM
    MDPM.CONSULTORIO AS CONSULTORIO_MED_DPM
    MDPM.TURNO TURNO_MED_DPM
    ORISOL.DES_ORIGEN_SOLIC_INC_MAT
    ESTSOL.DES_ESTATUS_SOLIC_INC_MAT
    ESTVAL.DES_ESTADO_VALORACION
    CASE
        WHEN ESTVAL.DES_ESTADO_VALORACION = 'APROBADA' THEN 1 ELSE 0
    END AS Valoracion_Aprobada,
    CASE
        WHEN ESTVAL.DES_ESTADO_VALORACION = 'RECHAZADA' THEN 1 ELSE 0
    END AS Valoracion_Rechazada,
    VAL.fec_registro_alta Fecha_Alta_Valorac,
    VAL.fec_registro_actualizado Fecha_Act_Valorac,
    INCAPACIDAD.REF_FOLIO_INCAPACIDAD,
    INCAPACIDAD.IND_ENVIO_NSSA,
    INCAPACIDAD.FEC_ENVIO_NSSA
    CASE
        WHEN INCAPACIDAD.FEC_ENVIO_NSSA IS NOT NULL THEN INCAPACIDAD.FEC_ENVIO_NSSA - SOLIC.FEC_REGISTRO_ALTA
        WHEN INCAPACIDAD.FEC_ENVIO_NSSA IS NULL THEN sysdate - SOLIC.FEC_REGISTRO_ALTA
    END AS Dias_Para_Valoracion
INCAPACIDAD.REF_REGISTRO_NSSA
IMT_SOLIC_INCAP_MATERNAL SOLIC
IMT_ASEGURADA_MAT ASEG                       ON SOLIC.CVE_ID_SOLIC_INCAP_MATERNAL = ASEG.CVE_ID_SOLIC_INCAP_MATERNAL
IMT_INFO_ADSCRIPCION_ASEGURADA ADSCRIP   ON ASEG.CVE_ID_ASEGURADA_IM = ADSCRIP.CVE_ID_ASEGURADA_IM
IMC_BANCO_MAT BANCO                           ON ASEG.CVE_ID_BANCO_IM = BANCO.CVE_ID_BANCO_IM
IMC_CONTROL_NATAL_NSS ATENIMSS                ON SOLIC.CVE_ID_CTRL_NATAL_NSS = ATENIMSS.CVE_ID_CTRL_NATAL_NSS
IMT_VALORACION_MEDICA VAL                    ON SOLIC.CVE_ID_SOLIC_INCAP_MATERNAL = VAL.CVE_ID_SOLIC_INCAP_MATERNAL
IMC_ESTADO_VALORACION ESTVAL                 ON VAL.CVE_ID_ESTADO_VALORACION = ESTVAL.CVE_ID_ESTADO_VALORACION
IMT_MOTIVO_RECHAZO_VALORACION MOTRECHAZO  ON VAL.CVE_ID_VALORACION_MEDICA = MOTRECHAZO.CVE_ID_VALORACION_MEDICA
IMC_MOTIVO_RECHAZO CATMOTRECHAZO ON MOTRECHAZO.CVE_ID_MOTIVO_RECHAZO = CATMOTRECHAZO.CVE_ID_MOTIVO_RECHAZO
IMC_MEDICO_ST MST                             ON VAL.CVE_ID_MEDICO_ST = MST.CVE_ID_MEDICO_ST
IMC_MEDICO_DPM MDPM                           ON VAL.CVE_ID_MEDICO_DPM = MDPM.CVE_ID_MEDICO_DPM
IMC_ORIGEN_SOLIC_INC_MAT ORISOL              ON SOLIC.CVE_ID_ORIGEN_SOLIC_INC_MAT = ORISOL.CVE_ID_ORIGEN_SOLIC_INC_MAT 
IMC_ESTATUS_SOLIC_INC_MAT ESTSOL             ON SOLIC.CVE_ID_ESTATUS_SOLIC_INC_MAT = ESTSOL.CVE_ID_ESTATUS_SOLIC_INC_MAT
IMT_INCAPACIDAD INCAPACIDAD                   ON SOLIC.CVE_ID_SOLIC_INCAP_MATERNAL = INCAPACIDAD.CVE_ID_SOLIC_INCAP_MATERNAL
--TURNO
DIT_UMF_CONSULTORIO_TURNO CONSTUR  ON GF.CVE_ID_UMF_CONS_TURNO_MED = CONSTUR.CVE_ID_UMF_CONS_TURNO          
AND SOLIC.FEC_REGISTRO_BAJA IS NULL
ORDER BY 2, 3 ASC;
 
SOLIC.CVE_ID_SOLIC_INCAP_MATERNAL
VAL.CVE_ID_VALORACION_MEDICA
VAL.OBSE_NOTA_MEDICA
MOTRECHAZO.CVE_ID_MOTIVO_RECHAZO
MOTRECHAZO.FEC_REGISTRO_ALTA
CATMOTRECHAZO.DES_MOTIVO_RECHAZO
IMT_SOLIC_INCAP_MATERNAL SOLIC
IMT_VALORACION_MEDICA VAL            ON SOLIC.CVE_ID_SOLIC_INCAP_MATERNAL = VAL.CVE_ID_SOLIC_INCAP_MATERNAL
IMT_MOTIVO_RECHAZO_VALORACION MOTRECHAZO   ON VAL.CVE_ID_VALORACION_MEDICA = MOTRECHAZO.CVE_ID_VALORACION_MEDICA
IMC_MOTIVO_RECHAZO CATMOTRECHAZO      ON MOTRECHAZO.CVE_ID_MOTIVO_RECHAZO = CATMOTRECHAZO.CVE_ID_MOTIVO_RECHAZO
ORDER BY 1, 2, 3;
